@extends('site.layout')
@section('title', 'Portal Dashboard | '.$settings->short_name)
@section('content')
<section class="bg-white"><div class="site-container py-10 sm:py-14"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-[.16em] text-[var(--brand-600)]">Secure School Portal</p><h1 class="mt-2 font-display text-4xl font-semibold text-[var(--brand-800)]">Welcome, {{ $user->name }}</h1><p class="mt-2 text-sm text-[var(--ink-soft)]">Account: {{ ucfirst($kind) }}</p></div><form action="{{ route('logout') }}" method="post">@csrf<button class="rounded-md border border-[var(--border)] px-4 py-2 text-sm font-semibold text-[var(--brand-800)]">Sign out</button></form></div>
@if($kind === 'student')
    @if($profile)<div class="mt-7 rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-5"><p><strong>Student number:</strong> {{ $profile->student_number }}</p><p><strong>Class:</strong> {{ $profile->schoolClass?->name ?? 'Not assigned' }} @if($profile->arm) · {{ $profile->arm->name }}@endif</p></div>@endif
    <section class="mt-9"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Published results</h2>@if($results->isEmpty())<p class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-5 text-sm text-[var(--ink-soft)]">No published results are available for this account yet.</p>@else<div class="mt-4 overflow-x-auto rounded-lg border border-[var(--border)]"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-[var(--surface-alt)]"><tr><th class="p-3">Session</th><th class="p-3">Term</th><th class="p-3">Subject</th><th class="p-3">Total</th><th class="p-3">Grade</th><th class="p-3">Report</th></tr></thead><tbody>@foreach($results as $result)<tr class="border-t border-[var(--border)]"><td class="p-3">{{ $result->academicSession?->name }}</td><td class="p-3">{{ $result->academicTerm?->name }}</td><td class="p-3">{{ $result->subject?->name }}</td><td class="p-3">{{ $result->total_score }}</td><td class="p-3">{{ $result->grade ?? '—' }}</td><td class="p-3"><a class="font-semibold text-[var(--brand-700)] underline" href="{{ route('results.report', $result) }}">View report card</a></td></tr>@endforeach</tbody></table></div>@endif</section>
@elseif($kind === 'parent')
    <section class="mt-8"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Linked children</h2>@if($children->isEmpty())<p class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-5 text-sm text-[var(--ink-soft)]">No student profiles are linked to this parent account. Please contact the school office.</p>@else<div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($children as $child)<article class="rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-5"><h3 class="font-display text-xl font-semibold text-[var(--brand-800)]">{{ $child->fullName() }}</h3><p class="mt-1 text-sm text-[var(--ink-soft)]">{{ $child->student_number }} · {{ $child->schoolClass?->name ?? 'Class not assigned' }} @if($child->arm) · {{ $child->arm->name }}@endif</p></article>@endforeach</div>@endif</section>
    <section class="mt-9"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Linked children’s published results</h2>@if($results->isEmpty())<p class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-5 text-sm text-[var(--ink-soft)]">No published results are available for linked children yet.</p>@else<div class="mt-4 overflow-x-auto rounded-lg border border-[var(--border)]"><table class="w-full min-w-[740px] text-left text-sm"><thead class="bg-[var(--surface-alt)]"><tr><th class="p-3">Student</th><th class="p-3">Session</th><th class="p-3">Term</th><th class="p-3">Subject</th><th class="p-3">Total</th><th class="p-3">Grade</th><th class="p-3">Report</th></tr></thead><tbody>@foreach($results as $result)<tr class="border-t border-[var(--border)]"><td class="p-3">{{ $result->student?->fullName() }}</td><td class="p-3">{{ $result->academicSession?->name }}</td><td class="p-3">{{ $result->academicTerm?->name }}</td><td class="p-3">{{ $result->subject?->name }}</td><td class="p-3">{{ $result->total_score }}</td><td class="p-3">{{ $result->grade ?? '—' }}</td><td class="p-3"><a class="font-semibold text-[var(--brand-700)] underline" href="{{ route('results.report', $result) }}">View</a></td></tr>@endforeach</tbody></table></div>@endif</section>
@elseif($kind === 'teacher')
    <section class="mt-8"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Assigned classes &amp; subjects</h2>@if($assignments->isEmpty())<p class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-5 text-sm text-[var(--ink-soft)]">No active class/subject assignments are linked to this teacher account.</p>@else<div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($assignments as $assignment)<article class="rounded-lg border border-[var(--border)] bg-[var(--surface-alt)] p-5"><h3 class="font-display text-xl font-semibold text-[var(--brand-800)]">{{ $assignment->schoolClass?->name }} @if($assignment->arm) · {{ $assignment->arm->name }}@endif</h3><p class="mt-1 text-sm text-[var(--ink-soft)]">{{ $assignment->subject?->name }}</p></article>@endforeach</div><a href="{{ route('results.entry') }}" class="mt-6 inline-flex rounded-md bg-[var(--brand-700)] px-5 py-3 text-sm font-semibold text-white">Enter assessment scores</a>@endif</section>
@else
    <section class="mt-8"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Administration</h2><p class="mt-2 max-w-3xl text-sm leading-relaxed text-[var(--ink-soft)]">Management tools are limited to permissions granted by the school administrator. Sensitive roles and actions are not available to ordinary accounts.</p><div class="mt-5 flex flex-wrap gap-3">@if($user->can('manage website content') || $user->can('manage results') || $user->can('manage payments'))<a href="{{ url('/admin') }}" class="rounded-md bg-[var(--brand-700)] px-5 py-3 text-sm font-semibold text-white">Open management console</a>@endif@if($user->can('enter assigned results'))<a href="{{ route('results.entry') }}" class="rounded-md border border-[var(--border)] px-5 py-3 text-sm font-semibold text-[var(--brand-800)]">Enter scores</a>@endif</div>
    @if($user->can('publish results') && isset($pendingResults) && $pendingResults->isNotEmpty())<h3 class="mt-9 font-display text-xl font-semibold text-[var(--brand-800)]">Pending result review</h3><div class="mt-3 space-y-3">@foreach($pendingResults as $pending)<div class="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-[var(--border)] p-4 text-sm"><span>{{ $pending->student?->fullName() }} · {{ $pending->subject?->name }} · {{ $pending->academicTerm?->name }} · {{ $pending->total_score }} ({{ $pending->grade ?? 'N/O' }})</span><form method="post" action="{{ route('results.publish', $pending) }}" data-confirm="Publish this result to the student and linked parent portal?">@csrf<button class="rounded bg-[var(--brand-700)] px-4 py-2 font-semibold text-white">Publish result</button></form></div>@endforeach</div>@endif
    @if($activity->isNotEmpty())<h3 class="mt-9 font-display text-xl font-semibold text-[var(--brand-800)]">Recent audit events</h3><ul class="mt-3 space-y-2">@foreach($activity as $event)<li class="rounded border border-[var(--border)] p-3 text-sm"><strong>{{ $event->event }}</strong> · {{ $event->created_at?->format('M j, Y H:i') }}</li>@endforeach</ul>@endif
    </section>
@endif

@if(in_array($kind, ['student', 'parent'], true))
    <section class="mt-10"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">School fees</h2>
    @if($fees->isEmpty())<p class="mt-4 rounded-lg border border-dashed border-[var(--border)] p-5 text-sm text-[var(--ink-soft)]">There are no unpaid fee assignments for this account.</p>
    @else<div class="mt-4 overflow-x-auto rounded-lg border border-[var(--border)]"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-[var(--surface-alt)]"><tr>@if($kind === 'parent')<th class="p-3">Student</th>@endif<th class="p-3">Fee</th><th class="p-3">Amount</th><th class="p-3">Due date</th><th class="p-3">Payment options</th></tr></thead><tbody>@foreach($fees as $fee)<tr class="border-t border-[var(--border)]">@if($kind === 'parent')<td class="p-3">{{ $fee->student?->fullName() }}</td>@endif<td class="p-3">{{ $fee->feeType?->name ?? 'School fee' }}@if($fee->description)<span class="block text-xs text-[var(--ink-soft)]">{{ $fee->description }}</span>@endif</td><td class="p-3">{{ $fee->currency }} {{ number_format((float)$fee->amount_due, 2) }}</td><td class="p-3">{{ $fee->due_date?->format('M j, Y') ?? '—' }}</td><td class="p-3">@forelse($gatewayOptions as $gateway)<form method="post" action="{{ route('payments.checkout', ['assignment' => $fee->id, 'gateway' => $gateway['driver']]) }}" class="inline-block mr-2" data-confirm="Continue to the secure {{ $gateway['name'] }} checkout to pay this school fee?">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button class="mb-1 rounded-md bg-[var(--brand-700)] px-3 py-2 text-xs font-semibold text-white">Pay with {{ $gateway['name'] }}</button></form>@empty<span class="text-xs text-[var(--ink-soft)]">Online checkout is not configured by the school. Contact the office for payment instructions.</span>@endforelse</td></tr>@endforeach</tbody></table></div>@endif
    @if($payments->isNotEmpty())<h3 class="mt-7 font-display text-xl font-semibold text-[var(--brand-800)]">Recent payment activity</h3><div class="mt-3 overflow-x-auto rounded-lg border border-[var(--border)]"><table class="w-full min-w-[650px] text-left text-sm"><thead class="bg-[var(--surface-alt)]"><tr>@if($kind === 'parent')<th class="p-3">Student</th>@endif<th class="p-3">Amount</th><th class="p-3">Method</th><th class="p-3">Status</th><th class="p-3">Receipt</th><th class="p-3">Date</th></tr></thead><tbody>@foreach($payments as $payment)<tr class="border-t border-[var(--border)]">@if($kind === 'parent')<td class="p-3">{{ $payment->student?->fullName() }}</td>@endif<td class="p-3">{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</td><td class="p-3">{{ ucfirst($payment->gateway) }}</td><td class="p-3">{{ $payment->status === 'successful' ? 'Verified' : ($payment->status === 'pending' ? 'Awaiting verification' : ucfirst($payment->status)) }}</td><td class="p-3">{{ $payment->receipt?->receipt_number ?? '—' }}</td><td class="p-3">{{ $payment->created_at?->format('M j, Y') }}</td></tr>@endforeach</tbody></table></div>@endif
    </section>
@elseif($kind === 'admin' && $user->can('manage payments') && $payments->isNotEmpty())
    <section class="mt-10"><h2 class="font-display text-2xl font-semibold text-[var(--brand-800)]">Recent payment transactions</h2><div class="mt-4 overflow-x-auto rounded-lg border border-[var(--border)]"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-[var(--surface-alt)]"><tr><th class="p-3">Student</th><th class="p-3">Amount</th><th class="p-3">Method</th><th class="p-3">Status</th><th class="p-3">Receipt</th></tr></thead><tbody>@foreach($payments as $payment)<tr class="border-t border-[var(--border)]"><td class="p-3">{{ $payment->student?->fullName() }}</td><td class="p-3">{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</td><td class="p-3">{{ ucfirst($payment->gateway) }}</td><td class="p-3">{{ ucfirst($payment->status) }}</td><td class="p-3">{{ $payment->receipt?->receipt_number ?? '—' }}</td></tr>@endforeach</tbody></table></div></section>
@endif
</div></section>
@endsection
