<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Student Academic Result · {{ $student->fullName() }}</title><style>
@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,Arial,sans-serif;color:#1a1a1a;font-size:10px;margin:0}.toolbar{display:flex;justify-content:flex-end;gap:8px;margin:0 auto 10px;max-width:1100px}.toolbar a,.toolbar button{padding:8px 12px;border:0;border-radius:4px;background:#5a121c;color:white;text-decoration:none;font-size:12px}.sheet{max-width:1100px;margin:auto;border:1px solid #b8b2ad;padding:18px;background:#fff}.header{display:flex;align-items:center;gap:14px;border-bottom:2px solid #23100f;padding-bottom:10px}.logo{width:50px;height:50px;object-fit:contain}.school{text-align:center;flex:1}.school h1{font-size:19px;color:#5a121c;margin:0}.school p{margin:4px 0;color:#5b5652}.avatar{width:50px;height:50px;border-radius:50%;border:1px solid #ddd;display:flex;align-items:center;justify-content:center;font-size:20px;color:#5a121c}.title{text-align:center;font-size:14px;font-weight:bold;text-transform:uppercase;margin:12px 0}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:6px 12px;background:#fbf8f5;padding:9px;margin-bottom:10px}.meta strong{color:#5b5652}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin:10px 0}.summary div{padding:7px;background:#fbf8f5;border:1px solid #e7dfd8;text-align:center}.summary strong{display:block;font-size:13px;color:#5a121c;margin-top:2px}table{width:100%;border-collapse:collapse;margin:8px 0 12px}th{background:#5a121c;color:#fff;text-align:left}th,td{border:1px solid #d2cbc5;padding:5px 6px}td.center,th.center{text-align:center}.fail{color:#b91c1c;font-weight:bold}.remarks{display:grid;grid-template-columns:1fr 1fr;gap:10px}.remarks div{border:1px solid #e7dfd8;padding:8px;min-height:44px}.signatures{display:grid;grid-template-columns:1fr 1fr 1fr;gap:30px;margin-top:20px}.signatures div{border-top:1px solid #555;padding-top:4px;text-align:center}.foot{margin-top:10px;text-align:center;color:#777;font-size:8px}.muted{color:#6b625e}@media print{.no-print{display:none!important}.sheet{border:0;padding:0;max-width:none}body{font-size:9px}}
</style></head><body>
@if(empty($isPdf))<div class="toolbar no-print"><button type="button" data-print>Print report</button><a href="{{ route('results.report', $anchor) }}?download=pdf">Download PDF</a></div>@endif
<div class="sheet"><div class="header">@if($logoPath)<img class="logo" src="{{ empty($isPdf) ? asset('storage/'.$settings->logo_path) : 'file://'.$logoPath }}" alt="">@endif<div class="school"><h1>{{ $settings->school_name }}</h1>@if($settings->motto)<p><em>{{ $settings->motto }}</em></p>@endif<p>{{ $settings->address ?: '—' }} · {{ $settings->phone_primary ?: '—' }} · {{ $settings->email ?: '—' }}</p></div><div class="avatar">{{ mb_strtoupper(mb_substr($student->first_name,0,1)) }}</div></div>
<h2 class="title">Student Academic Result</h2><div class="meta"><div><strong>Student:</strong> {{ $student->fullName() }}</div><div><strong>Student ID:</strong> {{ $student->student_number }}</div><div><strong>Class:</strong> {{ $student->schoolClass?->name ?: '—' }}</div><div><strong>Arm:</strong> {{ $student->arm?->name ?: '—' }}</div><div><strong>Session:</strong> {{ $anchor->academicSession?->name ?: '—' }}</div><div><strong>Term:</strong> {{ $anchor->academicTerm?->name ?: '—' }}</div><div><strong>Gender:</strong> {{ $student->gender ?: '—' }}</div><div><strong>Date of Birth:</strong> {{ $student->date_of_birth?->format('M j, Y') ?: '—' }}</div></div>
<div class="summary"><div>Subjects offered<strong>{{ $offered->count() }}</strong></div><div>Total score<strong>{{ number_format($total,2) }}</strong></div><div>Average<strong>{{ $average }}%</strong></div><div>Overall grade<strong>{{ $overallGrade['grade'] }} · {{ $overallGrade['remark'] }}</strong></div><div>Pass / Fail<strong>{{ $passCount }} / {{ max(0,$offered->count()-$passCount) }}</strong></div></div>
<table><thead><tr><th>Subject</th><th class="center">CA ({{ $maxima['ca1']+$maxima['ca2']+$maxima['ca3'] }})</th><th class="center">Exam ({{ $maxima['exam'] }})</th><th class="center">Total ({{ $totalMax }})</th><th class="center">Grade</th><th>Remark</th><th class="center">Class average</th><th class="center">High / Low</th><th class="center">Position</th>@if($cumulative->contains(fn($row)=>$row['terms']>1))<th class="center">Annual total</th><th class="center">Annual average</th>@endif</tr></thead><tbody>
@if($offered->isEmpty())<tr><td colspan="11" class="center muted">No published results available for this term.</td></tr>@else @foreach($offered as $row)@php($stats = $subjectStats->get($row->subject_id))@php($year = $cumulative->get($row->subject_id))<tr><td>{{ $row->subject?->name ?: '—' }}</td><td class="center">{{ number_format((float)$row->ca1_score+(float)$row->ca2_score+(float)$row->ca3_score,2) }}</td><td class="center">{{ number_format((float)$row->exam_score,2) }}</td><td class="center">{{ number_format((float)$row->total_score,2) }}</td><td class="center {{ $settings->highlight_fail_grade && $row->grade === 'F' ? 'fail' : '' }}">{{ $row->grade ?: '—' }}</td><td>{{ $row->remark ?: '—' }}</td><td class="center">{{ $stats['class_average'] ?? '—' }}</td><td class="center">{{ $stats ? number_format($stats['highest'],2).' / '.number_format($stats['lowest'],2) : '—' }}</td><td class="center">{{ $stats ? $stats['position'].' / '.$stats['population'] : '—' }}</td>@if($cumulative->contains(fn($item)=>$item['terms']>1))<td class="center">{{ $year['total'] ?? '—' }}</td><td class="center">{{ $year ? $year['average'].'%'.($year['terms'] < 3 ? ' *' : '') : '—' }}</td>@endif</tr>@endforeach @endif
</tbody></table>
@if($cumulative->contains(fn($row)=>$row['terms']>1))<p class="muted">Annual totals average only terms with a saved, published score. * Fewer than three term scores were available.</p>@endif
<div class="summary"><div>Class position<strong>{{ $classRank ?: '—' }} / {{ $studentCount ?: '—' }}</strong></div><div>Arm position<strong>{{ $armRank ?: '—' }} / {{ $armCount ?: '—' }}</strong></div><div>Grade bands<strong>@foreach($bands as $band){{ $band['grade'] }} {{ $band['min_score'] }}–{{ $band['max_score'] }}@if(!$loop->last) · @endif @endforeach</strong></div><div>Pass percentage<strong>{{ $settings->pass_percentage }}%</strong></div><div>Publication<strong>{{ $anchor->published_at?->format('M j, Y') ?: '—' }}</strong></div></div>
@if($ratings->isNotEmpty())<h3>Affective &amp; psychomotor ratings</h3><table><thead><tr><th>Trait</th><th>Category</th><th class="center">Rating</th><th>Descriptor</th></tr></thead><tbody>@foreach($ratings as $rating)<tr><td>{{ $rating->trait?->name ?: '—' }}</td><td>{{ ucfirst($rating->trait?->category ?: '—') }}</td><td class="center">{{ $rating->rating }} / 5</td><td>{{ [1=>'Poor',2=>'Fair',3=>'Average',4=>'Good',5=>'Excellent'][$rating->rating] ?? '—' }}</td></tr>@endforeach</tbody></table>@endif
<div class="remarks"><div><strong>Class teacher’s remark</strong><br>{{ $termRemark?->teacher_remark ?: $offered->first()?->teacher_remark ?: '—' }}</div><div><strong>Principal’s remark</strong><br>{{ $termRemark?->principal_remark ?: $offered->first()?->principal_remark ?: '—' }}</div></div>
<div class="signatures"><div>Class teacher</div><div>Principal</div><div>Parent / Guardian</div></div><p class="foot">Generated privately for {{ $student->fullName() }} · {{ now()->format('Y-m-d H:i') }}</p></div></body></html>
