@extends('site.layout')
@section('title', 'Score Entry | '.$settings->short_name)
@section('content')
<section class="bg-white"><div class="site-container max-w-6xl py-12"><a href="{{ route('portal.dashboard') }}" class="text-sm font-semibold text-[var(--brand-700)] underline">← Portal</a><h1 class="mt-4 font-display text-4xl font-semibold text-[var(--brand-800)]">Enter assessment scores</h1><p class="mt-3 max-w-3xl text-sm leading-relaxed text-[var(--ink-soft)]">Scores are checked against the assigned class, arm, subject, term and configured maxima on the server. Saved records remain pending until a results administrator publishes them.</p>
@if($errors->any())<div role="alert" class="mt-5 rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
@if($assignments->isEmpty())<p class="mt-8 rounded-lg border border-dashed border-[var(--border)] p-6 text-[var(--ink-soft)]">No class/subject assignments are available for this account.</p>@else<div class="mt-8 space-y-8">@foreach($assignments as $assignment)
<article class="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-alt)] p-6"><div class="mb-5"><p class="text-xs font-semibold uppercase tracking-wide text-[var(--brand-600)]">{{ $assignment->schoolClass?->name }}@if($assignment->arm) · {{ $assignment->arm->name }}@endif</p><h2 class="mt-1 font-display text-2xl font-semibold text-[var(--brand-800)]">{{ $assignment->subject?->name }}</h2></div>
<form method="post" action="{{ route('results.store') }}" class="grid gap-4 md:grid-cols-2">@csrf<input type="hidden" name="assignment_id" value="{{ $assignment->id }}">
<label class="text-sm font-medium">Student<select name="student_id" required class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"><option value="">Choose a student</option>@foreach($eligible as $student)@if((int)$student['class_id'] === (int)$assignment->school_class_id && ($assignment->arm_id === null || (int)$student['arm_id'] === (int)$assignment->arm_id))<option value="{{ $student['id'] }}" @selected(old('student_id') == $student['id'])>{{ $student['label'] }}</option>@endif @endforeach</select></label>
<label class="text-sm font-medium">Academic session<select name="academic_session_id" required class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5">@foreach($sessions as $session)<option value="{{ $session->id }}" @selected(old('academic_session_id') == $session->id)>{{ $session->name }}@if($session->is_active) (active)@endif</option>@endforeach</select></label>
<label class="text-sm font-medium">Academic term<select name="academic_term_id" required class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"><option value="">Choose a term</option>@foreach($sessions as $session)@foreach($session->terms as $term)<option value="{{ $term->id }}" @selected(old('academic_term_id') == $term->id)>{{ $session->name }} · {{ $term->name }}@if($term->is_current) (current)@endif</option>@endforeach @endforeach</select></label>
<div class="grid grid-cols-2 gap-3 md:col-span-2 lg:grid-cols-4"><label class="text-sm font-medium">CA 1<input name="ca1_score" type="number" min="0" max="100" step="0.01" value="{{ old('ca1_score', 0) }}" class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"></label><label class="text-sm font-medium">CA 2<input name="ca2_score" type="number" min="0" max="100" step="0.01" value="{{ old('ca2_score', 0) }}" class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"></label><label class="text-sm font-medium">CA 3<input name="ca3_score" type="number" min="0" max="100" step="0.01" value="{{ old('ca3_score', 0) }}" class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"></label><label class="text-sm font-medium">Exam<input name="exam_score" type="number" min="0" max="100" step="0.01" value="{{ old('exam_score', 0) }}" class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"></label></div>
<label class="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" name="is_offered" value="1" checked class="rounded border-[var(--border)]"> Student was offered this subject</label>
<label class="text-sm font-medium md:col-span-2">Teacher remark (optional)<input name="teacher_remark" maxlength="255" value="{{ old('teacher_remark') }}" class="mt-1 block w-full rounded-md border border-[var(--border)] bg-white px-3 py-2.5"></label>
<div class="md:col-span-2"><button class="rounded-md bg-[var(--brand-700)] px-5 py-3 text-sm font-semibold text-white">Save pending score</button></div>
</form></article>
@endforeach</div>@endif
</div></section>
@endsection
